"""
plot_imaginary_eigenvalues.py

Visualize imaginary parts of eigenvalues vs alpha on a log scale.

Reads HDF5 files generated by plot_imaginary_eigenvalues.jl and creates
publication-quality plots showing Im(ω) as a function of α for various spins.

Usage:
    python scripts/plot_imaginary_eigenvalues.py
"""

import h5py
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import glob

# Configuration
DPI = 150
FIGSIZE = (12, 8)

# Quantum level definitions
levels = [
    (2, 1, 1),   # 211
    (2, 1, -1),  # 21-1
    (3, 1, 1),   # 311
    (3, 2, 2),   # 322
]

def get_level_name(n, l, m):
    """Create a readable level name"""
    m_str = str(abs(m))
    return f"{n}{l}{m_str}"

def load_imaginary_data(filename):
    """Load imaginary eigenvalue data from HDF5 file"""
    data = {}
    try:
        with h5py.File(filename, 'r') as f:
            # Get all spin keys
            for spin_key in f.keys():
                if spin_key.startswith('spin_'):
                    spin = float(spin_key.split('_')[1])
                    group = f[spin_key]

                    alpha = np.array(group['alpha'])
                    im_part = np.array(group['im_part'])

                    data[spin] = {
                        'alpha': alpha,
                        'im_part': im_part,
                    }
        return data
    except Exception as e:
        print(f"Error loading {filename}: {e}")
        return {}

def create_plot(level_data, level_name, n, l, m, output_file=None):
    """
    Create a plot of imaginary part vs alpha on log scale.

    Args:
        level_data: Dict of spin -> {alpha, im_part}
        level_name: String name like "211"
        n, l, m: Quantum numbers
        output_file: Optional filename to save plot
    """

    fig, ax = plt.subplots(figsize=FIGSIZE)

    # Color map for different spins
    spins = sorted(level_data.keys())
    colors = plt.cm.viridis(np.linspace(0, 1, len(spins)))

    for i, spin in enumerate(spins):
        data = level_data[spin]
        alpha = data['alpha']
        im_part = data['im_part']

        # Filter out nan or inf values
        mask = np.isfinite(im_part)
        alpha_clean = alpha[mask]
        im_clean = im_part[mask]

        if len(alpha_clean) > 0:
            # Plot on log scale
            # Only plot positive values
            positive_mask = im_clean > 0
            if np.any(positive_mask):
                ax.loglog(alpha_clean[positive_mask], im_clean[positive_mask],
                         marker='o', markersize=4, linewidth=2,
                         label=f'a = {spin}', color=colors[i])

    # Formatting
    ax.set_xlabel(r'$\alpha = \mu M G_N$', fontsize=14, fontweight='bold')
    ax.set_ylabel(r'$|\mathrm{Im}(\omega)|$', fontsize=14, fontweight='bold')
    ax.set_title(f'Imaginary Eigenvalue Part: Level ({n},{l},{m})',
                 fontsize=16, fontweight='bold')

    ax.grid(True, which='both', alpha=0.3, linestyle='--')
    ax.legend(fontsize=11, loc='best', framealpha=0.9)

    # Set reasonable axis limits
    if len(spins) > 0 and len(level_data[spins[0]]['alpha']) > 0:
        all_alphas = np.concatenate([level_data[spin]['alpha'] for spin in spins])
        all_ims = np.concatenate([level_data[spin]['im_part'] for spin in spins])

        alpha_min, alpha_max = np.min(all_alphas), np.max(all_alphas)
        im_min_positive = np.min(all_ims[all_ims > 0])
        im_max = np.max(all_ims[all_ims > 0])

        ax.set_xlim(alpha_min * 0.9, alpha_max * 1.1)
        ax.set_ylim(im_min_positive * 0.5, im_max * 2)

    plt.tight_layout()

    # Save figure
    if output_file is None:
        output_file = f"plots/imaginary_eigenvalues_{level_name}.png"

    Path(output_file).parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_file, dpi=DPI, bbox_inches='tight')
    print(f"Saved: {output_file}")

    plt.close()

def create_comparison_plot():
    """Create a single plot comparing all levels"""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.flatten()

    for idx, (n, l, m) in enumerate(levels):
        ax = axes[idx]
        level_name = get_level_name(n, l, m)
        level_str = f"{n}{l}{abs(m)}"
        filename = f"data/imaginary_eigenvalues_{level_str}.h5"

        level_data = load_imaginary_data(filename)
        if not level_data:
            ax.text(0.5, 0.5, f'No data for level ({n},{l},{m})',
                   ha='center', va='center', transform=ax.transAxes)
            continue

        spins = sorted(level_data.keys())
        colors = plt.cm.viridis(np.linspace(0, 1, len(spins)))

        for i, spin in enumerate(spins):
            data = level_data[spin]
            alpha = data['alpha']
            im_part = data['im_part']

            # Filter valid data
            mask = np.isfinite(im_part) & (im_part > 0)
            alpha_clean = alpha[mask]
            im_clean = im_part[mask]

            if len(alpha_clean) > 0:
                ax.loglog(alpha_clean, im_clean, marker='o', markersize=3,
                         linewidth=1.5, label=f'a = {spin}', color=colors[i])

        ax.set_xlabel(r'$\alpha = \mu M G_N$', fontsize=11)
        ax.set_ylabel(r'$|\mathrm{Im}(\omega)|$', fontsize=11)
        ax.set_title(f'Level ({n},{l},{m})', fontsize=12, fontweight='bold')
        ax.grid(True, which='both', alpha=0.3, linestyle='--')
        ax.legend(fontsize=9)

    plt.suptitle('Imaginary Eigenvalue Parts for 1 Solar Mass Black Hole',
                fontsize=14, fontweight='bold', y=1.00)
    plt.tight_layout()

    output_file = "plots/imaginary_eigenvalues_comparison.png"
    Path(output_file).parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_file, dpi=DPI, bbox_inches='tight')
    print(f"Saved: {output_file}")

    plt.close()

def main():
    """Main plotting routine"""
    print("Plotting imaginary eigenvalue data...")

    # Check if data directory exists
    if not Path("data").exists():
        print("ERROR: data/ directory not found. Run plot_imaginary_eigenvalues.jl first.")
        return

    # Create plots directory
    Path("plots").mkdir(exist_ok=True)

    # Plot each level individually
    for n, l, m in levels:
        level_name = get_level_name(n, l, m)
        level_str = f"{n}{l}{abs(m)}"
        filename = f"data/imaginary_eigenvalues_{level_str}.h5"

        print(f"\nProcessing level ({n},{l},{m})...")

        level_data = load_imaginary_data(filename)
        if level_data:
            create_plot(level_data, level_name, n, l, m)
        else:
            print(f"  WARNING: No data found for {filename}")

    # Create comparison plot
    print("\nCreating comparison plot...")
    create_comparison_plot()

    print("\nDone!")

if __name__ == "__main__":
    main()
